family = "vsicon-dark"
output_file = "vsicon-dark.ttf"
version_major = 1
version_minor = 0
color_format = "cbdt"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = [ "D:\\GitHub\\vsicon\\font-src\\svg\\dark\\ea60.svg", "D:\\GitHub\\vsicon\\svg\\1f3a3.svg"]

[master.regular.position]
wght = 400
